#ifndef PARADOX_SOFTWARE_CPP_DESKTOP_DEFINES_HPP
#define PARADOX_SOFTWARE_CPP_DESKTOP_DEFINES_HPP

#include <paradox-application/defines.hpp>

#ifdef PARADOX_DESKTOP_STATIC
    #define PARADOX_DESKTOP_API
#elif PARADOX_DESKTOP_BUILD_DLL
    #define PARADOX_DESKTOP_API PARADOX_EXPORT
#else
    #define PARADOX_DESKTOP_API PARADOX_IMPORT
#endif

#endif