#ifndef PARADOX_SOFTWARE_C_APPLICATION_DEFINES_H
#define PARADOX_SOFTWARE_C_APPLICATION_DEFINES_H

#include <paradox-platform/defines.h>

#ifdef PARADOX_APPLICATION_STATIC
    #define PARADOX_APPLICATION_API
#elif PARADOX_APPLICATION_BUILD_DLL
    #define PARADOX_APPLICATION_API PARADOX_EXPORT
#else
    #define PARADOX_APPLICATION_API PARADOX_IMPORT
#endif

#endif