#ifndef PARADOX_SOFTWARE_C_HEADER_APPLICATION_DEFINES
#define PARADOX_SOFTWARE_C_HEADER_APPLICATION_DEFINES

#include <paradox-platform/defines.h>

#ifdef PARADOX_DESKTOP_STATIC
    #define PARADOX_APPLICATION_API
#elif PARADOX_DESKTOP_BUILD_DLL
    #define PARADOX_APPLICATION_API PARADOX_EXPORT
#elif PARADOX_MOBILE_STATIC
    #define PARADOX_APPLICATION_API
#elif PARADOX_MOBILE_BUILD_DLL
    #define PARADOX_APPLICATION_API PARADOX_EXPORT
#else
    #define PARADOX_APPLICATION_API PARADOX_IMPORT
#endif

#endif