#ifndef PARADOX_WORKS_CPP_APPLICATION_DEFINES_HPP
#define PARADOX_WORKS_CPP_APPLICATION_DEFINES_HPP

#include <paradox-platform/defines.hpp>

#ifdef PARADOX_APPLICATION_STATIC
    #define PARADOX_APPLICATION_API
#elif PARADOX_APPLICATION_BUILD_DLL
    #define PARADOX_APPLICATION_API PARADOX_EXPORT
#else
    #define PARADOX_APPLICATION_API PARADOX_IMPORT
#endif

#endif