#ifndef PARADOX_SOFTWARE_C_HEADER_DESKTOP_DEFINES
#define PARADOX_SOFTWARE_C_HEADER_DESKTOP_DEFINES

#include <paradox-platform/defines.h>

#ifdef PARADOX_DESKTOP_STATIC
    #define PARADOX_DESKTOP_API
#elif PARADOX_DESKTOP_BUILD_DLL
    #define PARADOX_DESKTOP_API PARADOX_EXPORT
#else
    #define PARADOX_DESKTOP_API PARADOX_IMPORT
#endif

#endif